"""Martin — Build webs with Python, Flutter-style."""

__version__ = "0.5.0"

from .app import App, Router, PageConfig
from . import backend
from . import fx
from .styles import (
    CSS,
    StyleBase,
    resolve_styles,
    Border,
    Padding,
    Margin,
    Shadow,
    Size,
    Background,
    TextStyle,
    Opacity,
    Overflow,
    Cursor,
    Glass,
    GradientText,
    MeshBackground,
    Colors,
)
from .widgets import (
    # Layout
    Container,
    Row,
    Column,
    Grid,
    Stack,
    Card,
    Section,
    Spacer,
    Divider,
    # Text
    Text,
    Heading,
    Paragraph,
    Link,
    Code,
    # Media
    Image,
    Video,
    Icon,
    IconPack,
    Avatar,
    # Interaction
    Button,
    TextField,
    TextArea,
    Checkbox,
    Select,
    MultiSelect,
    Slider,
    ColorPicker,
    DatePicker,
    RadioGroup,
    NumberInput,
    TimePicker,
    ProgressBar,
    Rating,
    FileInput,
    FormGroup,
    # Feedback
    Badge,
    Alert,
    # Navigation
    NavBar,
    SideMenu,
    Footer,
    Breadcrumb,
    Tabs,
    # Data
    Table,
    # Overlay
    Modal,
    # Utility
    Raw,
    Script,
    Stylesheet,
    StyleTag,
    ThemeToggle,
    SafeArea,
    # Compound
    WordCloud,
    Map,
    Timeline,
    TimelineItem,
    Hero,
    Gallery,
    GalleryItem,
    Carousel,
    CarouselItem,
    CookieBanner,
    CookieCategory,
    Accordion,
    AccordionItem,
    Testimonials,
    TestimonialItem,
    SlideCarousel,
    SlideItem,
    Pricing,
    PricingPlan,
    FAQ,
    FAQItem,
    Chart,
    ChartDataset,
    Calendar,
    CalendarEvent,
)

__all__ = [
    "__version__",
    "fx",
    "backend",
    "App",
    "Router",
    "PageConfig",
    "CSS",
    "StyleBase",
    "resolve_styles",
    "Border",
    "Padding",
    "Margin",
    "Shadow",
    "Size",
    "Background",
    "TextStyle",
    "Opacity",
    "Overflow",
    "Cursor",
    "Glass",
    "GradientText",
    "MeshBackground",
    "Colors",
    "Container",
    "Row",
    "Column",
    "Grid",
    "Stack",
    "Card",
    "Section",
    "Spacer",
    "Divider",
    "Text",
    "Heading",
    "Paragraph",
    "Link",
    "Code",
    "Image",
    "Video",
    "Icon",
    "IconPack",
    "Avatar",
    "Button",
    "TextField",
    "TextArea",
    "Checkbox",
    "Select",
    "MultiSelect",
    "Slider",
    "ColorPicker",
    "DatePicker",
    "RadioGroup",
    "NumberInput",
    "TimePicker",
    "ProgressBar",
    "Rating",
    "FileInput",
    "FormGroup",
    "Badge",
    "Alert",
    "NavBar",
    "SideMenu",
    "Footer",
    "Breadcrumb",
    "Tabs",
    "Table",
    "Modal",
    "Raw",
    "Script",
    "Stylesheet",
    "StyleTag",
    "ThemeToggle",
    "SafeArea",
    "WordCloud",
    "Map",
    "Timeline",
    "TimelineItem",
    "Hero",
    "Gallery",
    "GalleryItem",
    "Carousel",
    "CarouselItem",
    "CookieBanner",
    "CookieCategory",
    "Accordion",
    "AccordionItem",
    "Testimonials",
    "TestimonialItem",
    "SlideCarousel",
    "SlideItem",
    "Pricing",
    "PricingPlan",
    "FAQ",
    "FAQItem",
    "Chart",
    "ChartDataset",
    "Calendar",
    "CalendarEvent",
]
