[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "martin-framework"
version = "0.3.0"
description = "Build webs with pure Python"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

[project.optional-dependencies]
dev = ["watchdog>=3.0"]

[project.scripts]
martin = "martin.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["martin*"]
