[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "martin-framework"
version = "0.5.0"
description = "Build webs with pure Python"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

[project.optional-dependencies]
dev = ["watchdog>=3.0"]

[project.scripts]
martin = "martin.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["martin*"]
