import unittest

from martin import (
    App,
    Button,
    ColorPicker,
    DatePicker,
    Link,
    MultiSelect,
    NavBar,
    Router,
    Select,
    Text,
)
from martin.widgets.navigation import Tabs
from martin.widgets.overlay import Modal


class AccessibilityTests(unittest.TestCase):
    def test_modal_has_dialog_a11y_attrs(self):
        Modal._SCRIPT_READY = False
        html = Modal(id="confirm", title="Confirmar", children=[Text("Body")]).render()
        self.assertIn('role="dialog"', html)
        self.assertIn('aria-modal="true"', html)
        self.assertIn('aria-hidden="true"', html)
        self.assertIn('aria-labelledby="confirm_title"', html)
        self.assertIn('aria-label="Cerrar modal"', html)
        self.assertIn('tabindex="-1"', html)

    def test_tabs_have_roles_and_keyboard_support(self):
        html = Tabs(
            tabs=[("Uno", Text("A")), ("Dos", Text("B"))],
            default=0,
        ).render()
        self.assertIn('role="tablist"', html)
        self.assertIn('aria-label="Pestanas"', html)
        self.assertIn('role="tab"', html)
        self.assertIn('role="tabpanel"', html)
        self.assertIn('aria-selected="true"', html)
        self.assertIn('aria-hidden="false"', html)
        self.assertIn('ArrowRight', html)
        self.assertIn('ArrowLeft', html)

    def test_app_nav_burger_has_aria_state(self):
        router = Router()
        router.add("/", lambda: Text("Home"), title="Inicio")
        router.add("/about", lambda: Text("About"), title="About")
        app = App(router=router, hot_reload=False, theme_toggle=False)
        nav_html = app._nav_html("/")
        self.assertIn('aria-controls="_martin_nav_drawer"', nav_html)
        self.assertIn('aria-expanded="false"', nav_html)
        self.assertIn('id="_martin_nav_drawer"', nav_html)
        self.assertIn('setAttribute("aria-expanded"', nav_html)

    def test_autogenerated_aria_labels(self):
        btn_html = Button("Guardar").render()
        self.assertIn('aria-label="Guardar"', btn_html)

        link_html = Link("Inicio", href="/").render()
        self.assertIn('aria-label="Inicio"', link_html)

        nav_html = NavBar(brand=Text("Demo")).render()
        self.assertIn('aria-label="Barra de navegacion"', nav_html)
        self.assertIn("@media(max-width:840px)", nav_html)
        self.assertIn("overflow-x:clip", nav_html)

    def test_navbar_has_mobile_hamburger_by_default(self):
        html = NavBar(
            brand=Text("Demo"),
            links=[Link("Inicio", href="/")],
            actions=[Button("Entrar", variant="ghost")],
        ).render()
        self.assertIn('aria-label="Abrir menu"', html)
        self.assertIn("data-mobile-open=\"0\"", html)
        self.assertIn("_burger", html)
        self.assertIn("_menu", html)
        self.assertIn("flex-direction:column", html)
        self.assertIn("_links > *{display:block;width:100%}", html)
        self.assertIn("left:50%;transform:translateX(-50%)", html)

    def test_explicit_aria_label_override_wins(self):
        html = Button("Guardar", aria_label="Accion primaria").render()
        self.assertIn('aria-label="Accion primaria"', html)
        self.assertNotIn('aria-label="Guardar"', html)

        tabs_html = Tabs(
            tabs=[("Uno", Text("1"))],
            aria_label="Configuracion",
        ).render()
        self.assertIn('aria-label="Configuracion"', tabs_html)

    def test_modal_without_title_gets_default_label(self):
        Modal._SCRIPT_READY = False
        html = Modal(id="m2", children=[Text("Body")]).render()
        self.assertIn('aria-label="Dialogo"', html)

    def test_modal_runtime_helpers_are_present_even_if_flag_is_true(self):
        Modal._SCRIPT_READY = True
        html = Modal(id="m3", title="Demo", children=[Text("Body")]).render()
        self.assertIn("window.openModal", html)
        self.assertIn("window.closeModal", html)

    def test_select_defaults_and_roles(self):
        html = Select(
            options=[("es", "Español"), ("en", "English")],
            search=True,
            placeholder="Idioma",
        ).render()
        self.assertIn('role="combobox"', html)
        self.assertIn('aria-haspopup="listbox"', html)
        self.assertIn('aria-label="Idioma"', html)
        self.assertIn('role="option"', html)

    def test_multiselect_defaults_and_multiselectable(self):
        html = MultiSelect(
            options=["Python", "Rust"],
            values=["Python"],
            placeholder="Lenguajes",
        ).render()
        self.assertIn('aria-label="Lenguajes"', html)
        self.assertIn('aria-multiselectable="true"', html)
        self.assertIn('role="option"', html)
        self.assertIn('aria-selected="true"', html)

    def test_colorpicker_defaults(self):
        html = ColorPicker(label="Color de marca", presets=["#6366f1"]).render()
        self.assertIn('aria-label="Color de marca"', html)
        self.assertIn('aria-label="Color de marca en formato hexadecimal"', html)
        self.assertIn('aria-label="Preset #6366f1"', html)

    def test_datepicker_defaults_and_dialog_attrs(self):
        html = DatePicker(label="Fecha de nacimiento").render()
        self.assertIn('aria-label="Fecha de nacimiento"', html)
        self.assertIn('aria-haspopup="dialog"', html)
        self.assertIn('role="dialog"', html)
        self.assertIn('aria-modal="true"', html)

    def test_explicit_override_for_new_widgets(self):
        html = Select(options=["A"], aria_label="Selector custom").render()
        self.assertIn('aria-label="Selector custom"', html)

        html = DatePicker(aria_label="Calendario custom").render()
        self.assertIn('aria-label="Calendario custom"', html)


if __name__ == "__main__":
    unittest.main()
